### PR TITLE
Create new seperate types for actions

### PR DESCRIPTION
**Pull request by jbicker**
Fixes Incorrect AST generation with actions #297

### CODE REVIEW

**Review by msujew — COMMENTED** [review]
The changes look generally good to me. @Pluralia Do you also mind testing this with your grammar?

**Review by Pluralia — APPROVED** [review]

**Comment by Pluralia** [comment]
> Do you also mind testing this with your grammar?
I've already tested, @jbicker made a small fix and now everything is great.

**Review by msujew — APPROVED** [review]
@Pluralia Thanks! @jbicker Please address the outstanding comment, afterwards this is good to go :)

**Comment by spoenemann** [comment]
@jbicker could you check whether this fixes #378?

**Pull request merged**
