### PR TITLE
Moved langium config from package.json to its own json file

### LINKED ISSUE #219: Change default project to generate langium-config.json
I'd propose to generate a `langium-config.json` file instead of embedding the configuration in the package.json (though we can keep supporting both variants in the CLI). This way we can offer JSON editing support to users (#218).

### PR DESCRIPTION
**Pull request by jbicker**
To test it with the next version note the [contribution guidelines](https://github.com/langium/langium/blob/3b4b511b60d61cb807c187c17b1a794f6cf3986a/CONTRIBUTING.md#altered-langium-for-own-language-projects).
Fixes #219

### CODE REVIEW

**Review by spoenemann — COMMENTED** [review]
Thanks! When the configuration is in a separate file, you don't need the additional `"langium"` property block, so you can move its content one level higher.

**Comment by msujew** [comment]
FYI, I think the Langium config in the `langium` package itself can also be moved into its own file.

**Comment by jbicker** [comment]
> FYI, I think the Langium config in the `langium` package itself can also be moved into its own file.

Oh yes. Totally forgot about that this is also a langium language package itself.

**Review by spoenemann — APPROVED** [review]
:+1:

**Pull request merged**
