### PR TITLE
Update package lock file

### PR DESCRIPTION
**Pull request by msujew**
Updates our package lock file to version 3 used by newer versions of npm (>= 9.5.0). Also updates our locked dev dependencies.

### CODE REVIEW

**Comment by msujew** [comment]
@Yokozuna59 I haven't planned for that yet, but we can include that for the 2.0 release.

**Review by spoenemann — APPROVED** [review]
This will require a lot of devs to upgrade, but it's ok.

**Comment by msujew** [comment]
I'll delay merging this until https://github.com/langium/langium/pull/1125 is done.

**Comment by msujew** [comment]
I'll close this, as it's included in https://github.com/langium/langium/pull/1125.

**Pull request closed without merging**
