### PR TITLE
Set supertype on ruletypes even without fields or actions

### PR DESCRIPTION
**Pull request by jbicker**
Fixes https://github.com/langium/langium/issues/152

### CODE REVIEW

**Review by Pluralia — APPROVED** [review]
Great! Could you also commit the updated ast of the domainmodel example?

**Review by msujew — CHANGES_REQUESTED** [review]
I think we need another solution for this, since this exhibits a lot of unexpected behavior. For example, a rule such as `X: Y;` (where Y is a parser rule) shouldn't generate a type `X`, which is the reason for the whole field and action check.

**Comment by jbicker** [comment]
We discussed that with @spoenemann already. As far as I remember in case of AST generation such types should be generated. And as a designer of the Grammar and/or developer of a Code-Generator based on the AST I would expect to have such type inference.

**Comment by jbicker** [comment]
> since this exhibits a lot of unexpected behavior.

@msujew: What exactly wouldn't be expected?

**Comment by Pluralia** [comment]
How I understand, @msujew supposes different behavior when the rule `X` is alternatives and when it's a just "call", so 'X: Y' doesn't generate a type `X`, but `X: Y | Z` generates. Is it true?

**Comment by jbicker** [comment]
Ah, ok. Thanks for the hint, @Pluralia .
But even then as a designer of the grammar I would expect such type hierarchy. I mean, it is the decision or responsibility of the one who designs the grammar, or?

**Pull request merged**
